### ISSUE TITLE
MSSQL connector not able to verify a valid CA cert

### ISSUE THREAD

**Issue by danajuratoni** [elastic/connectors-python#1111]
## Bug Description
We tested the connection outside the connection outside of our MSSQL Connector using Python directly and it worked.  This is for our own test environment (not customer) so OK to use the credentials and cert file for reproduction.  The cert file used is linked below (it's the same file, except that I have renamed the extension before attaching to this issue).  The full error stack is included in the gist above.  Here's an excerpt.

```
[FMWK][12:49:03][WARNING] Something went wrong while executing query. Exception: [('SSL routines', '', 'certificate verify failed')]
[FMWK][12:49:03][WARNING] Retry count: 1 out of 3. Exception: [('SSL routines', '', 'certificate verify failed')]
[FMWK][12:49:06][WARNING] Something went wrong while executing query. Exception: [('SSL routines', '', 'certificate verify failed')]
[FMWK][12:49:06][WARNING] Retry count: 2 out of 3. Exception: [('SSL routines', '', 'certificate verify failed')]
[FMWK][12:49:11][WARNING] Something went wrong while executing query. Exception: [('SSL routines', '', 'certificate verify failed')]
[FMWK][12:49:11][WARNING] Retry count: 3 out of 3. Exception: [('SSL routines', '', 'certificate verify failed')]
[FMWK][12:49:11][CRITICAL] Can't connect to Microsoft SQL on elastic-sql-connector.database.windows.net
```

- When configuring this using MSSQL connector client using the contents of the [cert file](https://github.com/elastic/sdh-enterprise-search/files/11840263/yourdomain.txt), it doesn’t work so I don’t think the certificate itself is invalid, but it’s likely due to how we are loading the certificate from our configuration (perhaps we are requiring some specific manipulation of the content of the cert before it can be added as the configuration value for ssl_ca from the UI)?
- The following is the cert entry from the elastic connectors index for the configuration:

REDACTED. See the slack thread: https://elastic.slack.com/archives/C02AV5C8ZDE/p1687535501711019?thread_ts=1687519055.139339&cid=C02AV5C8ZDE

I suspect somewhere between adding the cert content to the UI and how we are storing and retrieving the cert content to pass into the Python calls is causing the cert to become invalid.  Is this a potential bug with the cert being a combined cert with a chain?

**Comment by prashant-elastic** [comment]
@danajuratoni We checked this on MS-SQL cloud instance which Tarek shared with us using the valid SSL certificate value but we are unable to reproduce this issue. Upon looking at the certificate value provided by you, it seems that there are three different SSL cert values validating a single host. So, if this is the case can you please provide us with the MS-SQL host on which you are facing this issue so our team will try to reproduce the same?

**Comment by seanstory** [comment]
@prashant-elastic no we can't, as the problem host is a customer machine. 
As far as I understand the customer's issue, the real problem is that they're not sure where to get the single cert from. Can y'all provide guidance on where our cert came from? Or @tarekziade if you were the one to set this up, perhaps you can provide some insight?

**Comment by seanstory** [comment]
Copying from [the slack thread](https://elastic.slack.com/archives/C02AV5C8ZDE/p1687537417765889?thread_ts=1687519055.139339&cid=C02AV5C8ZDE):

I think I found the bug.

The certfile that they're trying to submit has multiple certs inside of it.
```
-----BEGIN CERTIFICATE----- 
<KEYONE> 
-----END CERTIFICATE-----
-----BEGIN CERTIFICATE-----
<KEYTWO>
-----END CERTIFICATE-----
-----BEGIN CERTIFICATE-----
<KEYTHREE>
-----END CERTIFICATE-----
```

However, the get_pem_format() function seems to expect there will only be non-newline whitespace in the first and last lines, because the MSSQL connector calls it with max_split=1

From some REPL experiments, this leads to this cert being written out like:
```
 -----BEGIN CERTIFICATE----- 
<KEYONE> 
-----END
CERTIFICATE-----
-----BEGIN
CERTIFICATE-----
<KEYTWO>
-----END
CERTIFICATE-----
-----BEGIN
CERTIFICATE-----
<KEYTHREE>
-----END CERTIFICATE-----
```
Which is, of course, invalid
