### ISSUE TITLE
Clarify ECE Tests usage in documentation

### ISSUE THREAD

**Issue by ppf2** [elastic/connectors-python#356]
There are two sections in the developers guide where we mention end to end tests:

https://github.com/elastic/connectors-python/blob/main/docs/DEVELOPING.md#e2e-tests-https://github.com/elastic/connectors-python/blob/main/docs/DEVELOPING.md#e2e-tests

However, this command is really intended for internal developer testing only.  It makes the assumption that you are working against an Elasticsearch node that gets created on the fly in docker compose.  In other words, an Elastic Cloud user using the connector service against an Elasticsearch instance on Elastic Cloud should not run ftest because it will fail.

**Comment by praveen-elastic** [comment]
I agree, the ftest does fail if the Elastic cloud instance is used. It fails because the Elasticsearch cloud instance has `.elastic-connectors-v1` as the index. On the other hand, the local instance uses `.elastic-connectors` We can however make it working with a small change `.elastic-connectors` -> `.elastic-connectors*` and `.elastic-connectors-sync-jobs` -> `.elastic-connectors-sync-jobs*` in kibana.py file https://github.com/elastic/connectors-python/blob/9eb8af20f1f03900f3c99739d547d57386fcbb95/connectors/kibana.py#L21
