### ISSUE TITLE
System dep for the Oracle lib

### ISSUE THREAD

**Issue by tarekziade** [elastic/connectors-python#399]
## Bug Description

See https://buildkite.com/elastic/connectors-python-nightly/builds/276

solution:
https://gist.github.com/kimus/10012910

todo:

- [ ] fix the e2e test in `connectors-python`
- [ ] backport the system fix to `ent-search` cloud image build process

**Comment by tarekziade** [comment]
maybe we should use https://oracle.github.io/python-oracledb/ ?

**Comment by tarekziade** [comment]
also https://python-oracledb.readthedocs.io/en/latest/user_guide/appendix_c.html#upgrading83

**Comment by parth-crest** [comment]
Hey @tarekziade, we are planning to upgrade SQLAlchemy to version 2.0.0 which supports python-oracledb instead of cx_Oracle, where the need for installing oracle client would be eliminated.
We have created a [ticket](https://github.com/elastic/connectors-python/issues/400) on Github to track this change separately. Hence this issue will be taken care once that change is implemented.

**Comment by parth-crest** [comment]
Hey @tarekziade, After upgrading SQLAlchemy v2.0 This dependency is removed. We can close this bug once you verify that the build is passing successfully. 
We have verified and attached the screenshot.
![image (16)](https://user-images.githubusercontent.com/109953470/220064209-c29f8e83-99d3-42f0-b777-eb6c97a89a06.png)

**Comment by danajuratoni** [comment]
@tarekziade can this issue be closed?

**Comment by khusbu-crest** [comment]
@tarekziade Looking forward to your confirmation in order to close this issue.

**Comment by khusbu-crest** [comment]
@tarekziade Could you please look into this, we are waiting for your confirmation in order to close this issue?
