### ISSUE TITLE
Compatibility tests for running connector as native in Cloud

### ISSUE THREAD

**Issue by danajuratoni** [elastic/connectors-python#613]
### Problem Description
Perform compatibility tests to confirm following connectors are able to run as native in Cloud

1. Network Drive
2. Confluence
3. Jira
4. Oracle 
    - needs a "[Path of the oracle configuration files](https://github.com/elastic/connectors-python/blob/55b9f2ffb9c706ef94ab2ec35ba270af3bc97f79/docs/DEVELOPING.md#wallet_configuration_path)" which is not compatible to be deployed native in cloud.
5. Azure Blob Storage
6. Google Cloud Storage

7. S3 adjustments to replace this steps from the doc 

> Collect the information that is required to connect to your Amazon S3:
> Setup AWS configuration by installing [awscli](https://pypi.org/project/awscli/).
> 2. Add aws_access_key, aws_secret_key and region to run the connector.

### Proposed Solution / Alternatives
One option is to convert the configuration to a string in a configurable field.

For Oracle, the location of the wallet would need to be pre-defined in our docker container, then use the configuration to fill in the wallet.

**Comment by artem-shelkovnikov** [comment]
For AWS - why are we using local credentials/lib in the first place? I think there are python libraries that support instantiation of a client with credentials

**Comment by khushbu-elastic** [comment]
@danajuratoni Hereby, sharing the updates for compatibility tests for running connector as native in cloud:

1. Network drive - working fine
2. Confluence - working fine (for Confluence server & cloud)
3. Jira - working fine (for Jira server & cloud)
4. Azure Blob Storage - working fine
5. Google Cloud Storage - in-progress because of this [issue](https://github.com/elastic/connectors-python/issues/1044)
6. Oracle - working fine (for unsecured connection) but for the secured connection - needs a "[Path of the oracle configuration files](https://github.com/elastic/connectors-python/blob/55b9f2ffb9c706ef94ab2ec35ba270af3bc97f79/docs/DEVELOPING.md#wallet_configuration_path)" which is not compatible to be deployed native in cloud.
8. Amazon S3 - in-progress because of this [issue](https://github.com/elastic/connectors-python/issues/1032)

**Comment by danajuratoni** [comment]
@khushbu-elastic thanks for sharing the updade! This is great news for the first 4 connectors you listed which we can target to promote to native in 8.9!
Depending on the progress on the linked issue, #5 could also make it.
Let's add enhancement issues for #6 and #7 to v8.10.
cc: @sphilipse @efegurkan

**Comment by khushbu-elastic** [comment]
@danajuratoni  We have checked for GCS Connector as Native in cloud (during Internal testing) and it seems working fine too.

**Comment by praveen-elastic** [comment]
@khushbu-elastic @danajuratoni, fix the GCS issue, I had raised a PR and it got merged too 🚀 https://github.com/elastic/connectors-python/pull/1071

**Comment by khushbu-elastic** [comment]
@danajuratoni We have checked for Amazon S3 Connector as Native in cloud (during Internal testing) and it seems working fine too, after making the https://github.com/elastic/connectors-python/issues/1032 changes, internally.
We will be raising the PR for the same on github soon.

**Comment by danajuratoni** [comment]
Closing as done.
