### ISSUE TITLE
[Sharepoint] move Sharepoint REST API calls to Graph API calls

### ISSUE THREAD

**Issue by tarekziade** [elastic/connectors-python#760]
The connector uses the Sharepoint REST API, we should move to the Graph API to raise the rate limits

**Comment by tarekziade** [comment]
https://learn.microsoft.com/en-us/graph/throttling

**Comment by seanstory** [comment]
See the workplace search implementation in ruby:
- extractor: https://github.com/elastic/connectors-ruby/blob/8.3/lib/connectors_sdk/office365/extractor.rb
- client: https://github.com/elastic/connectors-ruby/blob/8.3/lib/connectors_sdk/office365/custom_client.rb

**Comment by akanshi-elastic** [comment]
@tarekziade  I checked the Graph APIs and it seems that oauth based authentication is not supported in  Sharepoint server because Graph API needs a token to authenticate and In sharepoint server we don't have any option to generate a token. Also found this forum regarding the support for graph API: https://learn.microsoft.com/en-us/answers/questions/1141800/graph-api-work-for-sharepoint-server

**Comment by akanshi-elastic** [comment]
Also we checked, the request/response for Graph APIs are different from REST APIS.
So we might have to put if else wherever we are calling an API. 

It would be the same as developing the new connector since response and APIs are different from the SharePoint server

**Comment by seanstory** [comment]
Does sharepoint server not offer the graph apis as an option? I had assumed it did, but that may be a bad assumption. In this case yes, I would agree, this would be best organized as two distinct connector implementations (perhaps with a shared base class for any shared concerns).

**Comment by parth-elastic** [comment]
If we are planning to use Graph APIs for SharePoint online and REST APIs for SharePoint Servers than it would be good if can consider those 2 as a separate connector since APIs and responses will be different. As @seanstory has rightly pointed out we can create a common class for the things which are common for both but we should not mix things in a single class.

WDYT ?? @nirav-elastic @tarekziade @danajuratoni @artem-shelkovnikov

**Comment by akanshi-elastic** [comment]
Also I see the documentation for Graph APIs and for using them we need to handle the application and delegated permissions as well for doing any API call. For reference: https://learn.microsoft.com/en-us/graph/api/site-get?view=graph-rest-1.0&tabs=http

**Comment by artem-shelkovnikov** [comment]
Can be closed - we now have a Sharepoint Online connector that does the job
