### ISSUE TITLE
MySQL connector requires SSL certificate path even with disable SSL = true

### ISSUE THREAD

**Issue by ppf2** [elastic/connectors-python#765]
On 8.7.0.  

There are two issues here:

1. On the UI, it allows you to set `Disable SSL` to true or false.

<img width="588" alt="image" src="https://user-images.githubusercontent.com/7216393/231637722-514ea29c-37dc-406a-9f67-a436bcc8528e.png">

One would think that setting `Disable SSL` to `true` is applicable for test mySQL instances where SSL is not enabled.  However, even if you have set it to `true`, it continues to throw the `SSL certificate' cannot be empty` error.

```
[FMWK][20:04:38][CRITICAL] Field validation errors: 'SSL certificate' cannot be empty.
```

Does it mean that the Disable SSL setting is only for disabling cert verification on the client side? i.e. we only support SSL-enabled MySQL instances? If so, it will be helpful to document accordingly and also update the display name of the `Disable SSL` setting on the UI to `Disable Certificate Verification`.

2. Our documentation is missing these SSL settings: https://www.elastic.co/guide/en/enterprise-search/current/connectors-mysql.html#connectors-mysql-configuration

(cc: @danajuratoni )

**Comment by danajuratoni** [comment]
@sphilipse can you please confirm this is a frontend issue?

**Comment by navarone-feekery** [comment]
This is a frontend issue with native MySQL connector. The label should be `Enable SSL`, that's what the backend logic is expecting.
It will be fixed by https://github.com/elastic/kibana/pull/154904

**Comment by navarone-feekery** [comment]
Note: this was introduced by the changes to configurable field keys here: https://github.com/elastic/connectors-python/pull/578

We should have a discussion about whether this will impact existing customers when they migrate, as MySQL connectors made in 8.7 will break from this change.

**Comment by ppf2** [comment]
Looks like a simple workaround is to just fake the path when SSL is not enabled:

<img width="190" alt="image" src="https://user-images.githubusercontent.com/7216393/231884725-a5818039-75bf-4e2f-b638-bfe49e2b79e5.png">

**Comment by parth-elastic** [comment]
> This is a frontend issue with native MySQL connector. The label should be Enable SSL

Yes, Correct. We have updated configuration field `ssl_disabled` to `ssl_enabled` in the backend as per our discussion with @danajuratoni [[Reference issue Here](https://github.com/elastic/connectors-python/issues/550)]

So We might need to update the label in the UI to fix this issue.

**Comment by navarone-feekery** [comment]
So the crux of this issue is that native connectors share logic in connectors-python with their non-native counterpart (e.g. native MySQL and custom MySQL), but they are created by different processes. Native connector configurable fields are set by Kibana. We should be aware next time that if there's a change to any configurable fields, a Kibana PR will also be required if that connector can be native.

**Comment by navarone-feekery** [comment]
Sorry I should have closed this; the issue was fixed by https://github.com/elastic/kibana/pull/154904
The "migration" issue is here: https://github.com/elastic/enterprise-search-team/issues/4219
(we won't be doing a migration, just alerting users to update their configuration structure through errors/documentation)

**Comment by navarone-feekery** [comment]
Memo: The PR that introduces this didn't backport to 8.7, so this is only an issue after 8.8.
