### ISSUE TITLE
[Sharepoint] mapper [size] cannot be changed from type [long] to [text]

### ISSUE THREAD

**Issue by llermaly** [elastic/connectors-python#939]
## Bug Description

The first time I run a crawl I see the following error: 

[FMWK][10:49:49][DEBUG] Task 1 - Sending a batch of 202 ops -- 7.12MiB
[FMWK][10:49:50][WARNING] Retry count: 2 out of 3. Exception: 400, message='Bad Request', url=URL('https://tenant.sharepoint.com/sites/site/_api/web/lists/getbytitle('Site%20Pages')/items?$select=Title,CanvasContent1,FileLeafRef&$filter=FileLeafRef+eq+'Some-File--Name'.aspx'')
[FMWK][10:49:50][DEBUG] Will retry in 8 seconds
[FMWK][10:49:53][ERROR] operation index failed, {'type': 'illegal_argument_exception', 'reason': 'mapper [size] cannot be changed from type [long] to [text]'}
[FMWK][10:49:53][ERROR] Exception found for task Task-290: mapper [size] cannot be changed from type [long] to [text]

In the next crawls I only see the bad request one.

### To Reproduce
1. Create a sharepoint site with lists/listitems 
2. Create a sharepoint crawl
3. Run the crawler from the local machine

## Expected behavior
We should not see mapping errors.

## Screenshots
N/A

## Environment
Elastic Cloud 8.8 (latest)
Sharepoint Python Connector main branch

## Additional context
While I write this I notice connector is 8.9 and Elastic Cloud is 8.8 so maybe that's related?

Also, potentially related to this one: 

https://github.com/elastic/connectors-python/issues/940

Thanks

**Comment by danajuratoni** [comment]
split from the old issue cc: @akanshi-elastic

**Comment by prashant-elastic** [comment]
@llermaly Just wanted to understand what do you mean by sharepoint crawl here? Because, we are not using any web crawler to run the connector. Instead we create an index with the help of "Use a connector" and run the connector to index the documents. We tried executing the connector using "Use a connector" option for sharepoint online and were not able to reproduce this issue at our end. Can you please let us know if we are missing anything here?
cc @danajuratoni

**Comment by akanshi-elastic** [comment]
Started working on the issue on 2nd june and raised a [PR](https://github.com/elastic/connectors-python/pull/1006) on github on 5th june
