### ISSUE TITLE
[Sharepoint] Missing ServerRelativeUrl field from Lists and ListItems

### ISSUE THREAD

**Issue by llermaly** [elastic/connectors-python#941]
## Bug Description
ServerRelativeUrl is not coming for Lists and ListItems 

### To Reproduce
1. Create sharepoint site with Lists and ListItems
2. Run the crawler
3. See documents, the ServerRelativeUrl field is not  coming

## Expected behavior
ServerRelativeUrl should come for both

## Screenshots
N/A

## Environment
* Elastic Cloud 8.8
* Connector main branch

## Additional context
Please @danajuratoni @seanstory  add the right labels.

**Comment by akanshi-elastic** [comment]
Hey @llermaly  , We are indexing `url` field rather than indexing `ServerRelativeUrl`.
In API response `ServerRelativeUrl` looks like this: `"/sites/enterprise1/Lists/new/Attachments/2/abc.txt"` but it doesn't make sense as it's not an absolute url  so user will not be able to click that link and we will not able to redirect him. 
With that reason we added host url  as a prefix to `ServerRelativeUrl` and stored it in a a field `url` . 
However if you want we can index `ServerRelativeUrl` and `url` both 
Let us know your thoughts for the same.

**Comment by llermaly** [comment]
This ticket is based on internal doc requirement so please go ahead and add the field, url is very useful as well. @danajuratoni correct me if I'm wrong

**Comment by danajuratoni** [comment]
Agreed that URL is useful and should be kept. We should have ServerRelativeUrl as well so users don't have to parse and remove the host for a relative path.

**Comment by prashant-elastic** [comment]
@danajuratoni We have tested it internally and found that ServerRelativeURL would not be indexed as a metadata for list item without attachment as we don't get the response for the same from the Sharepoint APIs. Please take a note of this.

**Comment by akanshi-elastic** [comment]
1. Worked on this issue on 25-05-2023 and raised a PR for this: https://github.com/elastic/connectors-python/pull/967
